# Nakama local development configuration
name: nakama1

logger:
  level: "DEBUG"

console:
  username: admin
  password: password

session:
  token_expiry_sec: 86400      # 24 hours

runtime:
  path: "/nakama/data/build"
  js_entrypoint: "index.js"
